### ISSUE TITLE
Required updates to README

### ISSUE THREAD

**Issue by spatialbits** [pauperpythonistas/python-geomark#34]
The readme currently doesn't include information about installing via `pip install geomark`.

The readme links to CHANGEME.md (should be "rst") near the bottom.

We could document the various Geomark api methods that we've implemented now.

**Comment by gregseb** [comment]
We also have a relative link to the LICENSE file.  In both cases on pypi, the links break, because they are relative and link to https://pypi.python.org/CHANGELOG.md  and  https://pypi.python.org/LICENSE

I suggest we update them to be absolute links to the files on the master branch"

- https://github.com/pauperpythonistas/python-geomark/blob/master/CHANGELOG.rst
- https://github.com/pauperpythonistas/python-geomark/blob/master/LICENSE
